hmcts/wa-task-management-api

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetWelcomeTest.java, src/integrationTest/resources/application-integration.yaml, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/CallbackControllerAdvice.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/ErrorLogger.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/RootControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/CallbackControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/ErrorLoggerTest.java
https://tools.hmcts.net/jira/browse/RWA-117
Added controller advice for exceptions.
Added env variable to control wether to also log the exception to the console.
```
[ ] Yes
[x ] No
```
=> RWA-117: Added controller advice for exceptions.

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskController.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskControllerTest.java
Added all initial task management endpoints with a NotImplementedException.
- GET /task/{task-id}
- POST /task (search with criteria)
- POST /task/{task-id}/complete
- POST /task/{task-id}/claim
- POST /task/{task-id}/unclaim
- POST /task/{task-id}/assign
```
[ ] Yes
[x ] No
```
=> Added all initial task management endpoints

build.gradle
Removed Lombok as it is not used and dependabot is trying to upgrade it
=> Removed Lombok as it is not used and dependabot is trying to upgrade it

charts/wa-task-management-api/values.aat.template.yaml
Enables stacktrace by default in aat. 
Update values.aat.template.yaml
```
[ ] Yes
[x ] No
```
=> Enables stacktrace by default in aat. 

.github/workflows/swagger.yml, .travis.yml
https://tools.hmcts.net/jira/browse/RWA-166
swagger for task management
```
[ ] Yes
[ x ] No
```
=> rwa-166 swagger for task management

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/clients/CamundaServiceApi.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/AddLocalVariableRequest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaLocalVariables.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/HistoryVariableInstance.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/PojoTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaLocalVariablesTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-53
Unclaim task
```
[ ] Yes
[ x ] No
```
=> unclaim task - 53

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/clients/CamundaServiceApi.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-55
Reassigning a task 
```
[ ] Yes
[ x ] No
```
=> reassignee task

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostClaimByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/TaskState.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/RestApiActions.java
https://tools.hmcts.net/jira/browse/RWA-214
Updating task state before claiming the task
Updated tests
```
[ ] Yes
[ x] No
```
=> RWA-214: Updating task state before claiming the task

Jenkinsfile_CNP, build.gradle, charts/wa-task-management-api/values.yaml, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetTaskByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostClaimByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUnclaimByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/access/AccessControlService.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/services/AuthorizationHeadersProvider.java
N/A
Updated Functional tests to include primaryLocation change.
Removed test accounts that are no longer needed.
```
[ ] Yes
[ x] No
```
=> Updated Functional tests to include primaryLocation change.

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-197
Upgrade azurerm to v2
```
[ ] Yes
[ x] No
```
=> RWA-197: Upgrade azurerm to v2

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-162
=> fix more code smells

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetTaskByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostClaimByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskAssignByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUnclaimByIdControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/services/AuthorizationHeadersProvider.java
N/a
- Fixes role-assignment user with no roles
```
[ ] Yes
[ x] No
```
=> Fixes role-assignment user with no roles

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetTaskByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostClaimByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskAssignByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUnclaimByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaQueryBuilder.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/services/AuthorizationHeadersProvider.java
https://tools.hmcts.net/jira/browse/RWA-111
Fix to check for no return from the DMN table
```
[ ] Yes
[ x ] No
```
=> added check for no return from DMN table

build.gradle
Bump tomcat version
```
[ ] Yes
[x ] No
```
=> Bump tomcat version

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/enums/Classification.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaProcessVariables.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/PojoTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/permission/PermissionEvaluatorServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaObjectMapperTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaProcessVariablesTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaValueTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/enums/AssigneeEnumTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaErrorDecoderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-291
```
[ ] Yes
[x ] No
```
=> added unit tests

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-305
```
[ ] Yes
[x ] No
```
=> updated the version to fix vulnerable issue

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java
https://tools.hmcts.net/jira/browse/RWA-212
Added 500 IT for get tasks
```
[ ] Yes
[ x ] No
```
=> Added 500 IT Test for getTask

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/idam/UserInfo.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/Common.java
N/A
Added Ignore json properties to UserInfo class to support sidam simulator
```
[ ] Yes
[ x] No
```
=> Sidam-simulator update

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-320
Added xui_webapp
```
[ ] Yes
[ x ] No
```
=> added xui-webapp access

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
=> Add debug log

README.md
=> Force re-build

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java
change log to info
```
[ ] Yes
[ ] No
```
=> change log to info

README.md, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java
print logs as json
```
[ ] Yes
[x ] No
```
=> print logs as json

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/Common.java
Added extra tests to cover scenarios.
Note: Need to clear polluted data in Camunda db first.
```
[ ] Yes
[x ] No
```
=> Added extra tests to cover scenarios

charts/wa-task-management-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-356
Bumping java chart version
```
[ ] Yes
[x ] No
```
=> bumping java chart version

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetTaskByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaVariableDefinition.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/Task.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskMapper.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/TaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/utils/CreateTaskVariableTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskMapperTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
Updated task managemnt
```
[ ] Yes
[ x ] No
```
=> added task variables

config/owasp/suppressions.xml
Remove redundant suppressions
```
[ ] Yes
[ x] No
```
=> Remove suppressions

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, infrastructure/main.tf, src/main/resources/bootstrap.yaml
Remove unused secrets
```
[ ] Yes
[ x] No
```
=> Remove unnecessary secret

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUnclaimByIdControllerTest.java
Improve test
```
[ ] Yes
[x ] No
```
=> Improve test

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/permission/AttributesValueVerifier.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/permission/PermissionEvaluatorService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/Assignment.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/permission/PermissionEvaluatorServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/AssignmentTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/enums/ActorIdTypeTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/enums/ClassificationTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/enums/GrantTypeTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/enums/RoleCategoryTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/enums/RoleTypeTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/request/RoleAssignmentRequestTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/request/RoleRequestTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/response/GetRoleAssignmentResponseTest.java
Added caseTypeId permission check. Code refactored to remove few suppress warnings.
```
[ ] Yes
[x ] No
```
=> Added caseTypeId permission check

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetTaskByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostClaimByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCancelByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/Common.java
=> fixed 403 FTs

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-424
Clean up unnecessary CVE'
```
[ ] Yes
[ x ] No
```
=> CVE review

Jenkinsfile_nightly, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-425
=> clean up secrets

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUnclaimByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-439
=> remove user id equal to task id check

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-457
=> return if task is added

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/search/SearchParameterKey.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaQueryBuilder.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskMapper.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaQueryBuilderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-467
Fix search-for-completable search by using processvariable taskId
```
[ ] Yes
[ x] No
```
=> RWA-467: Fix search-for-completable search by using processvariable taskId

Jenkinsfile_nightly
fix jenkins nightly build
```
[ ] Yes
[ x] No
```
=> fix jenkins nightly build

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RWA-475
Add launch darkly sdk key from vault
```
[ ] Yes
[ x] No
```
=> RWA-475: Add launch darkly sdk key from vault

audit.json
Add suppression for timestamp
```
[ ] Yes
[ x] No
```
=> Add suppression for timestamp

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/config/FeignConfiguration.java, src/main/resources/application.yaml
Enable debug log level
```
[ ] Yes
[x ] No
```
=> Enable debug log level

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetTaskByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostClaimByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskAssignByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCancelByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUnclaimByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/RootController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/ErrorMessage.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/SystemDateProvider.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/CallbackControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/ErrorMessageTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/SystemDateProviderTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootFunctionalBaseTest.java
Timestamp fixes:
Fixes an inconsistency that could happen when dealing with nanoseconds on the functional tests causing the test to fail.
```
[ ] Yes
[ x] No
```
=> Timestamp fixes

charts/wa-task-management-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-496
Bump hmctspublic java chart version
```
[ ] Yes
[x ] No
```
=> RWA-496: Bump hmctspublic java chart version

Jenkinsfile_CNP, build.gradle
Fix CVE-2021-22112
```
[ ] Yes
[ x] No
```
=> Fix CVE-2021-22112

src/functionalTest/resources/application-functional.yaml, src/functionalTest/resources/requests/ccd/case_data.json, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootFunctionalBaseTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
https://tools.hmcts.net/jira/browse/RWA-522
```
[ ] Yes
[ x] No
```
=> Added mandatory noc property to case data

Jenkinsfile_CNP, charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, src/main/resources/application.yaml, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootIntegrationBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-503
=> clean up duplicate idam api url

src/functionalTest/resources/application-functional.yaml, src/functionalTest/resources/requests/ccd/case_data.json, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootFunctionalBaseTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
=> using commont url for document store

audit.json
=> ignoring cross scripting endpoints

audit.json
=> Ignoring security scan issues

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/wa/TaskManagerUnClaimTaskConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerUnClaimTaskProviderTest.java
https://tools.hmcts.net/jira/browse/RWA-450
Add pact tests for unclaim endpoint
```
[ ] Yes
[ x] No
```
=> RWA-450: Add pact tests for unclaim endpoint

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchCriteriaPactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchForCompletablePactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskProviderTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetTaskByIdControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaVariableDefinition.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/Task.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/Warning.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/WarningValues.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskMapper.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaProcessVariablesTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/TaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/WarningTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/WarningValuesTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/utils/CreateTaskVariableTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskMapperTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
[RWA-529](https://tools.hmcts.net/jira/browse/RWA-529)
See ticket 
```
[ ] Yes
[ X] No
```
=> RWA-529 Add task warning attributes on Task & API

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCancelByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaQueryBuilder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
https://tools.hmcts.net/jira/browse/RWA-639
Add max tasks default of 50 when no pagination max tasks is given
```
[ ] Yes
[x ] No
```
=> RWA-639: Add max tasks default of 50 when no pagination max tasks is given

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/roleassignment/AmRoleAssignmentServiceConsumerTestForCreateRoleAssignment.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/roleassignment/AmRoleAssignmentServiceConsumerTestForDeleteByAssignmentId.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/roleassignment/AmRoleAssignmentServiceConsumerTestForGetActorById.java
Update providers on Pact test
```
[ ] Yes
[ x] No
```
=> Update providers on Pact test

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/wa/TaskManagementGetTasksBySearchCriteriaConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/wa/TaskManagerAssignTaskConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchCriteriaPactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerAssignTaskProviderTest.java, src/contractTest/resources/logback-test.xml, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/assigntaskcontroller/AssignTaskRequestTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/wataskconfigurationapi/camunda/AssigneeRequestTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/AssignTaskRequest.java
Fix failing pact tests
Fix /assign endpoint to temporarily accept user is as camelCase and snake case (backwards compatibility)
```
[ ] Yes
[ X] No
```
=> Fix failing pact tests

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/roleassignment/AmRoleAssignmentServiceConsumerTestForCreateRoleAssignment.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/roleassignment/AmRoleAssignmentServiceConsumerTestForDeleteByRoleAssignmentId.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/roleassignment/AmRoleAssignmentServiceConsumerTestForGetActorById.java
Fix provider names
```
[ ] Yes
[ ] No
```
=> Fix provider names

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/roleassignment/AmRoleAssignmentServiceConsumerTestForGetActorById.java
Update pact test state
```
[ ] Yes
[ ] No
```
=> Update pact state

build.gradle
=> Update tomcat to 9.0.50

audit.json
Ignore rule
```
[ ] Yes
[x ] No
```
=> Fix Nightly

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchCriteriaPactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchForCompletablePactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskProviderTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaVariableDefinition.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/Task.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskMapper.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaProcessVariablesTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/TaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/utils/CreateTaskVariableTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaHelpers.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskMapperTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/GivensBuilder.java
[RWA-585](https://tools.hmcts.net/jira/browse/RWA-585)
See ticket
```
[ ] Yes
[ X] No
```
=> RWA-585 Update task configuration to include case management category

build.gradle
=> fix vulnerabilities

Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/RWA-626
```
[ ] Yes
[x ] No
```
=> Updated nightly build to run FTs

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-692
=> authorise camunda

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/wataskconfigurationapi/controllers/TaskConfigurationControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/wataskconfigurationapi/services/RoleAssignmentServiceApiTest.java, src/integrationTest/resources/uk/gov/hmcts/reform/wataskmanagementapi/wataskconfigurationapi/variableextractors/roleAssignmentsResponseNewRoles.json
Added some integration test to test new role names
```
[ ] Yes
[x ] No
```
=> RWA-705: Added integration test to test new role names

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/repository/TaskResourceRepositoryTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/entities/TaskResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/entities/WorkTypeResource.java, src/main/resources/db/migration/V1.0.4__init_work_types.sql, src/main/resources/db/migration/V1.0.5__init_rename_work_type_values.sql, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/entities/WorkTypeResourceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapperTest.java
[RWA-680](https://tools.hmcts.net/jira/browse/RWA-680)
see ticket
```
[ ] Yes
[ X] No
```
=> RWA-680 Create new work_types table

audit.json
https://tools.hmcts.net/jira/browse/RWA-847
```
[ ] Yes
[x ] No
```
=> RWA-847 [SH] Adding required entries to ignore list in audit.json

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerCftTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/InitiateTaskRequestTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/InitiateTaskRequest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/TerminateTaskRequest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/entities/TaskAttribute.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/options/TerminateInfo.java
https://tools.hmcts.net/jira/browse/RWA-863
=> correct json annotations to make snake-case by default

build.gradle
Bump Springboot  minor version to fix CVE-2021-22096
```
[ ] Yes
[ x] No
```
=> Bump Springboot minor version to fix CVE-2021-22096

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUpdateTaskWithNotesControllerFailureTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/entities/NoteResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/NotesRequest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/advice/ApplicationProblemControllerAdviceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/InitiateTaskRequestTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/TerminateTaskRequestTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/enums/InitiateTaskOperationTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/enums/TaskAttributeDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/enums/TerminateReasonTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/DecisionTableTest.java
https://tools.hmcts.net/jira/browse/RWA-199
Rwa 199: Add Extra Tests to cover validation
```
[ ] Yes
[x ] No
```
=> Rwa 199: Add Extra Tests to cover validation

src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaHelpers.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/WorkTypesServiceTest.java
RWA-938
Fix nightly build failure due to mutation threshold dip
```
[ ] Yes
[ X] No
```
=> Increase mutation test coverage to fix nightly build failure

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/GetWorkTypesControllerCFTTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerFailureTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/ServiceMocks.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/RoleAttributeDefinition.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/WorkTypeQuerySpecification.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/repository/WorkTypeResourceRepository.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/WorkTypesService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/WorkTypeResourceSpecificationTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/WorkTypesServiceTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/RestApiActions.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/Common.java
[RWA-929](https://tools.hmcts.net/jira/browse/RWA-929)
See [RWA-929](https://tools.hmcts.net/jira/browse/RWA-929)
```
[ ] Yes
[X ] No
```
=> RWA-929 Add FTs to work types and improve query

audit.json
https://tools.hmcts.net/jira/browse/RWA-965
Ignore 100000_A Client Error response code was returned by the task/task-id/roles_GET
```
[ ] Yes
[X] No
```
=> ignore 100000_A Client Error response code roles_GET

src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/services/AuthorizationHeadersProvider.java
Create lawfirm user per ccd case
```
[ ] Yes
[x ] No
```
=> Create lawfirm user per ccd case

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerCFTTest.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-830
Add extra coverage for ACs:
Given a reviewAdditionalEvidence exist markEvidenceAsReviewed should complete reviewAdditionalEvidence task.
Given a reviewAdditionalHomeOfficeEvidence exist markEvidenceAsReviewed should complete reviewAdditionalHomeOfficeEvidence task
Minor change to logging for cleaner logs
Note: this PR depends on DMN Deployment https://github.com/hmcts/ia-task-configuration/pull/164
```
[ ] Yes
[ x] No
```
=> RWA-830: Extra Acs

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerCFTTest.java
https://tools.hmcts.net/jira/browse/RWA-957
interim fix to fix the failing test due to dependency on RWA-943
```
[ ] Yes
[x] No
```
=> RWA-957 interim fix to unblock dependency on RWA-943

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerCFTTest.java
=> Remove taskId assertion in FT

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchCriteriaPactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchForCompletablePactTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerCFTTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerCFTTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchController.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-812
```
[ ] Yes
[x ] No
```
=> RWA-812: Added integration test

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsController.java
https://tools.hmcts.net/jira/browse/RWA-1049
```
[ ] Yes
[ x] No
```
=> Fixed swagger for endpoint /roles

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskAssignByIdControllerCFTTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskAssignByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/exceptions/v2/enums/ErrorMessages.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/AssignTaskTest.java
https://tools.hmcts.net/jira/browse/RWA-1031
Improve error messages when verifying role-assignments for assignee and assigner
```
[ ] Yes
[x ] No
```
=> RWA-1031: Improve error messages when verifying role-assignments for assignee and assigner

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerFailureTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/ServiceMocks.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/RoleAttributeDefinition.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/WorkTypesService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/WorkTypesServiceTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/Common.java
[RWA-1106](https://tools.hmcts.net/jira/browse/RWA-1106)
[RWA-1106](https://tools.hmcts.net/jira/browse/RWA-1106)
```
[ ] Yes
[ X] No
```
=> RWA-1106 Work types not working when filter-by-user is true

src/main/resources/application.yaml
=> Add trace on cache

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskInitiateByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerCFTTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/role/entities/enums/RoleCategory.java
[RWA-1104](https://tools.hmcts.net/jira/browse/RWA-1104)
[RWA-1104](https://tools.hmcts.net/jira/browse/RWA-1104)
```
[ ] Yes
[ X] No
```
=> Change ADMINISTRATOR role_category to ADMIN

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/config/LaunchDarklyFeatureFlagProviderTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCancelByIdControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/InitiateTaskDbLockAndTransactionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/config/features/FeatureFlag.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/CancelTaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/CompleteTaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/CompleteTaskWithPrivilegeAndCompletionOptionsTest.java
[RWA-1051](https://tools.hmcts.net/jira/browse/RWA-1051)
[RWA-1051](https://tools.hmcts.net/jira/browse/RWA-1051)
```
[ ] Yes
[ X] No
```
=> RWA-1051 Remove R2 Cancellation feature flag

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1167
```
[ ] Yes
[X] No
```
=> suppress CWE-862

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/CftQueryService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/camunda/CamundaVariable.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/Task.java
https://tools.hmcts.net/jira/browse/RWA-1172
Some logs added to investigate Demo issue 
```
[ ] Yes
[X] No
```
=> some logs added for investigate debug

security.sh
https://tools.hmcts.net/jira/browse/RWA-1191
Updating security scanning URL from v2 swagger to v3
```
[ ] Yes
[x] No
```
=> RWA-1191 [SH] Updating zap-api scan to point to swagger v3

charts/wa-task-management-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-1199
Upgrading java chart version
```
[ ] Yes
[x] No
```
=> RWA-1199 [SH] Upgrading java chart version

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilter.java
=> Avoid hibernate n+1 issue when retrieving Tasks and Task Roles

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilter.java
=> removing n+1 fix

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilter.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilterTest.java
https://tools.hmcts.net/jira/browse/RWA-1223
RWA-1223 optional-check-added
```
[ ] Yes
[X] No
```
=> RWA-1223-optional-check-added

infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/variables.tf
Adding recommended DB params for perftesting
=> Adding perftest recommended parameters for db

audit.json
https://tools.hmcts.net/jira/browse/RWA-1191
```
[ ] Yes
[X] No
```
=> fix security issues

config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUpdateTaskWithNotesControllerCFTTest.java
Reverts hmcts/wa-task-management-api#543
=> Revert "RWA-1071 content type investigation"

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1265
CVE-2022-26520
CVE-2022-21724
```
[ ] Yes
[X] No
```
=> RWA-1265-CVE suppression

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/repository/TaskResourceRepositoryTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/entities/TaskResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/entities/TaskRoleResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/repository/TaskRoleResourceRepository.java
lazy loading the Task and TaskRole tables.
=> Lazy loading

config/owasp/suppressions.xml, infrastructure/perftest.tfvars
=> increasing DB Cores

src/contractTest/resources/json/case_data_map.json, src/functionalTest/resources/requests/ccd/case_data.json
https://tools.hmcts.net/jira/browse/RWA-1171
Update tests to look up postcode
```
[ ] Yes
[X] No
```
=> RWA-1171-add-waDummyPostcode

infrastructure/perftest.tfvars
bumping db cores for perftesting
=> moving db cores from 8 to 16 for perf testing only

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootContractProviderBaseTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/ccd/util/CcdConsumerTestBase.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchCriteriaPactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchForCompletablePactTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskRolePermissionsTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerAssignTaskProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerCancelTaskProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerClaimTaskProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerCompleteTaskProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerUnClaimTaskProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java
https://tools.hmcts.net/jira/browse/RWA-1353
```
[ ] Yes
[X] No
```
=> RWA-1353-pact-broker-fix

src/integrationTest/resources/scripts/data.sql, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/entities/TaskResourceSummary.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/CftQueryService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskResourceSummaryQueryBuilder.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskSearchQueryBuilder.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/taskconfiguration/controllers/TaskConfigurationController.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/CftQueryServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskResourceSpecificationTest.java
=> RWA-1347: Improve task search query

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/wa/CftQueryServiceAuthoriseUserTaskTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/wa/CftQueryServiceGetTaskTest.java, src/integrationTest/resources/scripts/authorise_user_data.sql, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilter.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/config/CustomPostgreSQL94Dialect.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilterTest.java
[RWA-1259](https://tools.hmcts.net/jira/browse/RWA-1259)
```
[ ] Yes
[x] No
```
=> RWA-1259 Add tests for multiple authorisation types

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1470
CVE-2022-22976 suppression:
https://nvd.nist.gov/vuln/detail/CVE-2022-22976
https://tanzu.vmware.com/security/cve-2022-22976
```
[ ] Yes
[x] No
```
=> CVE-2022-22976 suppression

audit.json
https://tools.hmcts.net/jira/browse/RWA-1445
Added new zaproxy ignore rule for new internal url
```
[ ] Yes
[x] No
```
=> RWA-1445: added new ignore rule to audit.json (zaproxy)

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/wataskconfigurationapi/controllers/PostTaskConfigurationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/MarkTasksReconfigurableControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/task/Task.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapper.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskReconfigurationService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/taskconfiguration/domain/entities/camunda/response/ConfigurationDmnEvaluationResponse.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/taskconfiguration/services/CaseConfigurationProviderService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapperTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskReconfigurationServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/taskconfiguration/services/CaseConfigurationProviderServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-1449
check task configuration DMN response before marking tasks for reconfiguration
```
[ ] Yes
[x] No
```
=> RWA-1449 check task configuration DMN response before marking tasks for reconfiguration

infrastructure/prod.tfvars, infrastructure/variables.tf, src/main/resources/db/migration/V1.0.14__add_tasks_table_index.sql
https://tools.hmcts.net/jira/browse/RWA-1285
RWA-1285-DB-cores infrastructure changes to environments
```
[ ] Yes
[X] No
```
=> RWA-1285-DB-cores

audit.json
https://tools.hmcts.net/jira/browse/RWA-1541
new ignore entry for audit.json
```
[ ] Yes
[x] No
```
=> RWA-1541: new ignore entry for audit.json

audit.json
https://tools.hmcts.net/jira/browse/RWA-1591
fixed typo in audit.json
```
[ ] Yes
[x] No
```
=> RWA-1591: fixed typo in audit.json

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1640
The suppression for the CVE problem CVE-2022-31569
```
[ ] Yes
[x ] No
```
=> CVE-2022-31569 suppression

src/main/resources/db/migration/V1.0.13__add_reconfigure_request_time_in_tasks.sql
https://tools.hmcts.net/jira/browse/RWA-1450
Fixed DB checksum error
```
[ ] Yes
[x] No
```
=> RWA-1450 fixed DB checksum error

build.gradle
https://tools.hmcts.net/jira/browse/RWA-1701
Fix CVE in postgres database driver
```
[ ] Yes
[X] No
```
=> RWA-1701 CVE fix

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-1722
added wa-workflow-api into exclusiveAccessClients
```
[ ] Yes
[x] No
```
=> RWA-1722: added wa-workflow-api into exclusiveAccessClients

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostClaimByIdControllerCFTTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerCFTTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerCFTTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostUnclaimByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskCompleteByIdControllerTest.java
[RWA-1624](https://tools.hmcts.net/jira/browse/RWA-1624)
```
[ ] Yes
[x] No
```
=> RWA-1624 clean up Role Assignments in AAT

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerCFTTest.java
[RWA-1521](https://tools.hmcts.net/jira/browse/RWA-1521)
```
[ ] Yes
[x] No
```
=> RWA-1521 revert

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskMarkReconfigureControllerCFTTest.java
https://tools.hmcts.net/jira/browse/RWA-1678
fixed failing test due to DMN changes
```
[ ] Yes
[x] No
```
=> RWA-1678 fixed failing test due to DMN changes

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/GetTaskByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskForSearchCompletionControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskSearchControllerTest.java
RWA-1787
Disable failing test 
```
[ ] Yes
[ ] No
```
=> Disable failing test (RWA-1787)

Jenkinsfile_CNP, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/GetTaskByIdControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskForSearchCompletionControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskSearchControllerTest.java
[RWA-1787](https://tools.hmcts.net/jira/browse/RWA-1787)
Enable disabled functional test for role assignmentId
```
[ ] Yes
[ ] No
```
=> Enable disabled functional test for role assignmentId(RWA-1787)

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskInitiateByIdControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/Common.java
https://tools.hmcts.net/jira/browse/RWA-1514
```
[ ] Yes
[X] No
```
=> RWA-1514-initiation FT added for reviewAppealSkeletonArgument with CTSC

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, src/functionalTest/resources/application-functional.yaml, src/integrationTest/resources/application-integration.yaml, src/main/resources/application.yaml
[RWA-1755](https://tools.hmcts.net/jira/browse/RWA-1755)
```
[ ] Yes
[ X] No
```
=>  RWA-1755 Enable Private law on WA

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, src/functionalTest/resources/application-functional.yaml, src/integrationTest/resources/application-integration.yaml, src/main/resources/application.yaml
[RWA-1726](https://tools.hmcts.net/jira/browse/RWA-1726)
see ticket
```
[ ] Yes
[ X] No
```
=> RWA-1726 Enable Civil's generalapplication case type

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-1793
Extended functional tests timeout period in night pipeline to 60 minutes
```
[ ] Yes
[x] No
```
=> RWA-1793: extended timeout period for functional tests

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskExecuteReconfigureControllerCFTTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskMarkReconfigureControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExecuteReconfigureTasksControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/MarkTasksReconfigurableControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskReconfigurationController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/entities/TaskOperation.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapper.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/ExecuteTaskReconfigurationService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskReconfigurationControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/ExecuteTaskReconfigurationServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java
[RWA-1824](https://tools.hmcts.net/jira/browse/RWA-1824)
See ticket
```
[ ] Yes
[X ] No
```
=> RWA-1824 Fix taskOperation initialisation issue

charts/wa-task-management-api/Chart.yaml, src/main/java/net/hmcts/taskperf/config/TaskPerfConfig.java, src/main/java/net/hmcts/taskperf/model/ClientFilter.java, src/main/java/net/hmcts/taskperf/service/RoleAssignmentHelper.java, src/main/resources/db/migration/V1.0.15__add_performance_indexing.sql, src/test/resources/search/search-02.yml, src/test/resources/search/search-03.yml
=> Rwa-1437-3

config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerCFTTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/wa/CftQueryServiceCompleteTaskTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskCompleteByIdControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/ServiceMocks.java, src/integrationTest/resources/scripts/wa/complete_task_data.sql, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/RoleAssignmentVerificationService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/taskconfiguration/services/TaskAutoAssignmentService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/AssignTaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/CancelTaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/ClaimTaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/CompleteTaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/CompleteTaskWithPrivilegeAndCompletionOptionsTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/GetTaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/UnclaimTaskTest.java
https://tools.hmcts.net/jira/browse/RWA-1544
New PR
```
[ ] Yes
[x] No
```
=> RWA 1544 new PR

.github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-1848
Added terraform support to renovate
```
[ ] Yes
[x] No
```
=> RWA-1848: Added terraform support to renovate

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/ExecuteTaskReconfigurationServiceTest.java, src/integrationTest/resources/scripts/wa/reconfigure_task_data.sql
[RWA-1827](https://tools.hmcts.net/jira/browse/RWA-1827)
see [RWA-1827](https://tools.hmcts.net/jira/browse/RWA-1827)
```
[ ] Yes
[X ] No
```
=> RWA-1827 Add IT for reconfiguration service

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskSearchControllerTest.java, src/main/java/net/hmcts/taskperf/model/ClientFilter.java, src/main/java/net/hmcts/taskperf/model/ClientQuery.java, src/main/java/net/hmcts/taskperf/service/TaskSearch.java, src/main/java/net/hmcts/taskperf/service/TaskSearchAdaptor.java, src/main/resources/db/migration/V2.0.00__add_performance_indexing.sql
=> Rwa-1437-4: available task only search 

audit.json, build.gradle
https://tools.hmcts.net/jira/browse/RWA-2028
This will stop the failure in the security sweep.
```
[ ] Yes
[x] No
```
=> RWA-2028 Add ignore line to audit.json

build.gradle
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1985&projectKey=RWA&view=detail&selectedIssue=RWA-2061&quickFilter=14713
Dependency check failure for task-management api nightly build failure:
Fix dependency issue on postgres jar file version
```
[ ] Yes
[X] No
```
=> RWA-2061 Dependency check failure for task-management api nightly build failure

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskInitiateByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/config/SnakeCaseFeignConfiguration.java
https://tools.hmcts.net/jira/browse/RWA-2092
Resolve due date calculation for local system
```
[ ] Yes
[ ] No
```
=> Resolve due date calculation (RWA-2092)

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CaseConfigurationProviderService.java
add more logs to task config process to help debugging PRL DEMO issue
```
[ ] Yes
[ X] No
```
=> Add logs to task configuration process

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateConfiguratorTest.java
https://tools.hmcts.net/jira/browse/RWA-1770
```
[ ] Yes
[x] No
```
=> RWA 1770 test for spring and autumn

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskInitiateByIdControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateConfiguratorTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/calendar/DueDateIntervalData.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateIntervalCalculator.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateIntervalReCalculator.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/WorkingDayIndicator.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CaseConfigurationProviderServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateIntervalCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateIntervalReCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/WorkingDayIndicatorTest.java
https://tools.hmcts.net/jira/browse/RWA-1948
```
[ ] Yes
[x] No
```
=> RWA 1948 Added next and previous

gradle/wrapper/gradle-wrapper.properties
RWA-2057 Updating Gradle Version to 7.6
```
[ ] Yes
[x] No
```
=> RWA-2057 Updating Gradle Version to 7.6

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2131
CVE issues are causing the nightly build to fail, some of these have been suppressed
```
[ ] Yes
[X] No
```
=> RWA-2131 - Fix nightly build faliures

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2143
Fixed CVE tomcat issue
```
[ ] Yes
[x] No
```
=> RWA-2134 - CVE fix tomcat

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/PublicHolidaysCollectionTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/exceptions/CalendarResourceInvalidException.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/exceptions/CalendarResourceNotFoundException.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/PublicHolidaysCollection.java
https://tools.hmcts.net/jira/browse/RWA-1740
Update after merge on master
```
[ ] Yes
[x] No
```
=> RWA 1740 update

src/main/resources/adhoc.migration/db-migration.sql
https://tools.hmcts.net/jira/browse/RWA-2068
Add adhoc db script for granular permission
```
[ ] Yes
[ ] No
```
=> Add adhoc db script (RWA-2068)

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/newinitiate/PostInitiateByIdControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapper.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapperTest.java
https://tools.hmcts.net/jira/browse/RWA-2045
RWA-2045 Configuration error - unrecognised permission
```
[ ] Yes
[X] No
```
=> RWA-2045 permission type validation

src/main/resources/db/migration/V1.0.23__add_tasks_table_granular_permission_index.sql
=> RWA-2198: Add task_role manage, claim and own index

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2289
Bump org.owasp.dependencycheck to version 8.1.0
```
[ ] Yes
[ x ] No
```
=> RWA-2289 Bump org.owasp.dependencycheck to version 8.1.0

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/config/FlywayConfiguration.java
=> fix invalid flyway history

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-2101
```
[ ] Yes
[ ] No
```
=> Turn off master syncing and deploy flexible databases

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CaseConfigurationProviderService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateCalculator.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateCalculator.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateIntervalCalculator.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/IntermediateDateIntervalCalculator.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/NextHearingDateIntervalCalculator.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/PriorityDateIntervalCalculator.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CaseConfigurationProviderServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateTypeConfiguratorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/NextHearingDateCalculatorTest.java
[RWA-2366](https://tools.hmcts.net/jira/browse/RWA-2366)
See [RWA-2366](https://tools.hmcts.net/jira/browse/RWA-2366)
```
[ ] Yes
[ X] No
```
=> RWA-2366 Add more log for debugging config dmn issues

build.gradle
[RWA-2427](https://tools.hmcts.net/jira/browse/RWA-2427)
Resolve cve issue in task management
```
[ ] Yes
[ ] No
```
=> Resolve cve issue

Jenkinsfile_CNP, config/owasp/suppressions.xml, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-2148
```
[ ] Yes
[x] No
```
=> RWA 2101 point to branch with fix for vnet

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RWA-2101
Stop syncing with perftest
```
[ ] Yes
[x] No
```
=> stop perftest syncing

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskTypeProviderTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/TaskTypeControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/DmnEvaluationServiceCacheTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/clients/CamundaServiceApi.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/response/GetTaskTypesResponse.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/DmnEvaluationService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskTypesService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskTypesControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/response/GetTaskTypesResponseTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/DmnEvaluationServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskTypesServiceTest.java
[RWA-2398](https://tools.hmcts.net/jira/browse/RWA-2398]
see ticket
```
[ ] Yes
[ X] No
```
=> RWA-2398 Task Types endpoint not working as specified

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-2101
```
[ ] Yes
[x] No
```
=> rwa 2101 add secrets to vault

infrastructure/main.tf, infrastructure/variables.tf, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskTypesServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-2101
Flexible DB server should deploy into all branches
```
[ ] Yes
[x] No
```
=> RWA 2101 deploy flexible server to master

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.aat.template.yaml, charts/wa-task-management-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-2148
```
[ ] Yes
[x] No
```
=> rwa 2148 release to prod

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RWA-2148
```
[ ] Yes
[x] No
```
=> turn sync on

.github/renovate.json
Reverts hmcts/wa-task-management-api#1042
=> Revert "Turning off renovate automerge for release MI Release."

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/DmnEvaluationServiceCacheTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/DmnEvaluationService.java
[RWA-2398](https://tools.hmcts.net/jira/browse/RWA-2398)
see ticket
```
[ ] Yes
[ X] No
```
=> Use dmn decision key for caching task types

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-2181
Just the config to deploy in perftest
```
[ ] Yes
[x] No
```
=> RWA added config for replica

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-2495
update ref to master in main.tf for flexible server
```
[ ] Yes
[x ] No
```
=> RWA-2495 update ref to master in main.tf

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2508
```
[ ] Yes
[ x ] No
```
=> RWA-2508: Checking CVE-2023-20863

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml
=> flyway scripts take long time to upgrade the search_index

charts/wa-task-management-api/values.aat.template.yaml, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-1835
Need to get rep onto staging
```
[ ] Yes
[x] No
```
=> Need to deploy to staging first

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateTypeConfiguratorForReconfigurationTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateCalculator.java
[RWA-2543](https://tools.hmcts.net/jira/browse/RWA-2543)
Resolve date calculation for reconfiguration
```
[ ] Yes
[ ] No
```
=> Resolve date calculation for reconfiguration

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchCriteriaPactTest.java
https://tools.hmcts.net/jira/browse/RWA-2581
Fix CVE
```
[ ] Yes
[ x ] No
```
=> RWA-2581: CVE Fix

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskReplicationMIControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/replicarepository/TaskAssignmentsRepository.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/MIReportingTestingController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/response/TaskAssignmentsResponse.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/TaskAssignmentsResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/TaskResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingService.java, src/main/resources/dbreplica/migration/V1.0.10__task_assignments_plsql.sql, src/main/resources/dbreplica/migration/V1.0.11__task_assignments_plsql.sql, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/MIReportingTestingControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingServiceTest.java
10 - Reporting DB: Populate assignment table
RWA-2382_10 task_assignments
```
[ ] Yes
[X] No
```
=> Rwa 2382 10

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskReplicationMIControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/ReportableTaskResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/TaskResource.java, src/main/resources/dbreplica/migration/V1.0.12__configure_replication_plsql.sql
https://tools.hmcts.net/jira/browse/RWA-2305
RWA-2305_11 final_state
```
[ ] Yes
[X] No
```
=> Rwa 2305 11

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchController.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-2589
added userId, caseId, list of completable tasks candidates for the invoking user.
```
[ ] Yes
[ x] No
```
=> RWA-2589 Enhance /search-for-completable logging

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2580
Suppress CVE
```
[ ] Yes
[ x ] No
```
=> RWA-2580: suppress CVE

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2650
Extended the Suppression End Date, waiting for Spring boot upgrade
```
[ ] Yes
[ x ] No
```
=> RWA-2650: extend the suppress CVE dates

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/main/resources/dbreplica/migration/V1.0.7__reportable_task_plsql.sql
=> RWA-2644: Calculate fields in auto-assign scenario when Task is Initiated

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchCriteriaPactTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExecuteReconfigurationTaskOperationControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ExecuteTaskReconfigurationService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ExecuteTaskReconfigurationServiceTest.java
https://tools.hmcts.net/jira/browse/COT-411
https://tools.hmcts.net/jira/browse/RWA-2666
```
[ ] Yes
[ ] No
```
=> COT-411: FPL reconfiguration bug fix

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/replicarepository/ReportableTaskRepository.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/config/db/FlywayReplicaMigrationConfiguration.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceRepository.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-2677
=> making MI integration tests consistent

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/ReportableTaskResource.java, src/main/resources/dbreplica/migration/V1.0.8__alter_reportable_task_plsql.sql, src/main/resources/dbreplica/migration/V1.0.9__reportable_task_plsql.sql
https://tools.hmcts.net/jira/browse/RWA-2656
https://tools.hmcts.net/jira/browse/RWA-2657
https://tools.hmcts.net/jira/browse/RWA-2658
https://tools.hmcts.net/jira/browse/RWA-2659
MI Related changes
```
[ ] Yes
[ x ] No
```
=> RWA-2657: mi reporting

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/ReplicaBaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/ReplicationCheckerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/replicarepository/TaskHistoryResourceRepository.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/enums/TaskOperationType.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/BaseTaskHistoryResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/TaskHistoryResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/TaskResource.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceRepository.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ReplicationChecker.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ReplicationCheckerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/TaskOperationServiceTest.java
=> RWA-2634: Detecting Replication Problems

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2693
Update dependency
```
[ ] Yes
[ x] No
```
=> RWA-2693: Fix CVE-2023-34034

infrastructure/main.tf
Flexible server replica-2 - AAT only
- To test and resolve current access issues with current replica.
```
[ ] Yes
[X] No
```
=> Flexible server replica-2 - AAT only

infrastructure/main.tf
test jit in AAT
```
[ ] Yes
[X] No
```
=> test jit in AAT

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerDeleteTaskProviderTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/DeleteTasksControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsController.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-2712
Revert changes made in
https://github.com/hmcts/wa-task-management-api/pull/1149
```
[ ] Yes
[x] No
```
=> RWA-2712 revert changes

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2750
Fix CVE-2023-20883 
```
[ ] Yes
[x] No
```
=> RWA-2750 Fix CVE-2023-20883 Fix

audit.json, build.gradle
https://tools.hmcts.net/jira/browse/RWA-2757
upgrade tomcat-embed version
```
[ ] Yes
[x] No
```
=> RWA-2757 tomcat-embed version upgrade

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2763
```
[ ] Yes
[ ] No
```
=> RWA-2763: Upgrade Java Logging to 6.0.1

.github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-2722
```
[ ] Yes
[ ] No
```
=> RWA-2722: Updated Renovate config

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagerDeleteTaskProviderTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/DeleteTasksControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsController.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskActionsControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-2712
PR to Modify delete task API.
```
[ ] Yes
[x] No
```
=> RWA-2712 Delete Task API Modification

README.md, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/ReplicaBaseTest.java, src/integrationTest/resources/application-integration.yaml, src/integrationTest/resources/application-replica.yaml, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/replicarepository/SubscriptionCreator.java, src/main/resources/application-replica.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-2720
Introduced subscription host and port as a config param
```
[ ] Yes
[ x ] No
```
=> Rwa 2664 1

infrastructure/main.tf, infrastructure/variables.tf
=> Try creating new db/schema from scratch

infrastructure/main.tf
=> Use master branch for replica-2

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/CleanUpSensitiveLogsService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/CleanUpSensitiveLogsServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-2638 
```
[ ] Yes
[ ] No
```
=> RWA-2638: Test exception correction

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-2772
Fix timing issues with Nightly build failure
```
[ ] Yes
[ x ] No
```
=> RWA-2772: Fixed timing issue with nightly test failures

charts/wa-task-management-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2816
Remove dependency on docker.io
```
[ ] Yes
[x] No
```
=> RWA-2816-Remove dependency on docker.io

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2834
Extend suppression date for CVE-2023-35116
```
[ ] Yes
[x] No
```
=> RWA-2834- Extend CVE suppression date

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/main/resources/dbreplica/migration/V1.0.16__alter_tasks_for_refresh.sql, src/main/resources/dbreplica/migration/V1.0.17__mark_tasks_for_refresh.sql, src/main/resources/dbreplica/migration/V1.0.18__get_report_refresh_request_times.sql
https://tools.hmcts.net/jira/browse/RWA-2825
https://tools.hmcts.net/jira/browse/RWA-2826
MI Changes to accommodate data fixes and/or refresh
```
[ ] Yes
[ x ] No
```
=> RWA-2825: Refresh reportable tasks changes

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2872
Upgrade tomcat to fix CVE
```
[ ] Yes
[x] No
```
=> RWA-2872 Upgrade tomcat to fix new CVE

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-2855
```
[ ] Yes
[ ] No
```
=> RWA-2855: Test fixes

src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/DecisionTableTest.java
https://tools.hmcts.net/jira/browse/RWA-2745
```
[ ] Yes
[ ] No
```
=> RWA-2745: Added tests to cover special chars

charts/wa-task-management-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2845
Migrating to Workload Identity
```
[ ] Yes
[x] No
```
=> RWA-2845 Migrating to Workload Identity

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2910
Fix  CVE-2023-35116
```
[ ] Yes
[x ] No
```
=> RWA-2910: FIX CVE CVE-2023-35116

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2870
Update publishResults settings in build.gradle
```
[ ] Yes
[x] No
```
=> RWA-2870: Update publishResults settings in build.gradle

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2994
Upgrade spring-security-rsa to v.1.11, tomcat to v.9.0.83
```
[ ] Yes
[x] No
```
=> RWA-2994: Fix CVE

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3020
Bump up of OWASP Version
```
[ ] Yes
[ x ] No
```
=> RWA-3020: upgrade owasp version

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3078
Failure - wa-task-management-api - 983 -- updated flexmark library to testImplementation
```
[ ] Yes
[x] No
```
=> changed to testImplementation

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3078
Removed aggregate function
```
[ ] Yes
[x] No
```
=> commented out aggregate

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-3079
Failure - nightly tests - wa-task-management-api - 872
```
[ ] Yes
[x] No
```
=> RWA-3079 Jenkins Nightly failure fix

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskRolePermissionsTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java
https://tools.hmcts.net/jira/browse/RWA-3084
RWA-3084 Refactoring in order to republish provider to pact broker
```
[ ] Yes
[ x ] No
```
=> Refactoring in order to republish provider to pact broker

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-3083
nightly failure initial fix
```
[ ] Yes
[x] No
```
=> RWA-3083 initial fix

src/main/resources/dbreplica/migration/V1.0.26__task_history_plsql.sql, src/main/resources/dbreplica/migration/V1.0.27__reportable_task_plsql.sql
https://tools.hmcts.net/jira/browse/RWA-2975
Add log statement in function
```
[ ] Yes
[x] No
```
=> RWA-2975 added additional log

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3087
Address CVE Issues
```
[ ] Yes
[ x ] No
```
=> RWA-3087: fix cve issues

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-3097
Failure nightly tests - wa-task-management-api - 894
```
[ ] Yes
[x] No
```
=> RWA-3097 Failure nightly tests

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3114
```
[ ] Yes
[X] No
```
=> RWA-3114: Upgrade Spring-Security-Config

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-3131
fix flaky tests
```
[ ] Yes
[ x ] No
```
=> RWA-3131: fix flaky tests

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3146
Address CVEs
```
[ ] Yes
[ x ] No
```
=> RWA-3146: address cve suppressions

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, src/functionalTest/resources/application-functional.yaml, src/integrationTest/resources/application-integration.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-3120
https://tools.hmcts.net/jira/browse/COT-438
```
[ ] Yes
[ ] No
```
=> RWA-3120: Whitelist PRIVATELAW_ExceptionRecord in PROD

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExecuteReconfigurationTaskOperationControllerTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapper.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapperTest.java
https://tools.hmcts.net/jira/browse/RWA-3166
Reconfigure task title
```
[ ] Yes
[x] No
```
=> RWA-3166 reconfigure task title

build.gradle, charts/wa-task-management-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-3210
```
[ ] Yes
[ x] No
```
=> RWA-3219: Upgrade postgresql

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3223
```
[ ] Yes
[X] No
```
=> RWA-3223: Extending Suppressions

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-3126
```
[ ] Yes
[ ] No
```
=> RWA-3126: spotInstance config added

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-3288
https://tools.hmcts.net/jira/browse/RWA-3288
```
[ ] Yes
[x] No
```
=> RWA-3288 Add a Functional Test to verify PRL scenario works

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, src/functionalTest/resources/application-functional.yaml, src/integrationTest/resources/application-integration.yaml, src/integrationTest/resources/application-replica.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-3215
```
[ ] Yes
[ ] No
```
=> RWA-3215: Whitelist SSCS on prod

src/main/resources/dbreplica/migration/V1.0.33__reportable_task_plsql.sql
https://tools.hmcts.net/jira/browse/RWA-3201
Update ET Service name
```
[ ] Yes
[x] No
```
=> RWA-3201 Update ET Service name

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3384
```
[ ] Yes
[x] No
```
=> RWA-3384: Extend Suppressions

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/db/PostgreExtendedSQLContainerProvider.java, src/integrationTest/resources/application-integration.yaml, src/integrationTest/resources/application-replica.yaml
https://tools.hmcts.net/jira/browse/RWA-3484
```
[ ] Yes
[x ] No
```
=> RWA-3485: Define DockerImageName

Jenkinsfile_CNP, Jenkinsfile_nightly, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/db/PostgreExtendedSQLContainerProvider.java, src/integrationTest/resources/application-integration.yaml, src/integrationTest/resources/application-replica.yaml
Reverts hmcts/wa-task-management-api#1266
Build failing
=> Revert "RWA-3485: Define DockerImageName"

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3494
```
[ ] Yes
[x ] No
```
=> RWA-3494: Extend suppressions

.github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-3490
=> Adding more fine tuning for renovate PRs

build.gradle, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/config/CustomLogBookConfiguration.java
https://tools.hmcts.net/jira/browse/RWA-3471
```
[ ] Yes
[x ] No
```
=> RWA:3471: Bump dependencies for Spring boot upgrade

build.gradle, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/RWA-3593
```
[ ] Yes
[x] No
```
=> RWA-3593: Extend Suppressions and upgrade dependencycheck and gradle

build.gradle, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/restrict/ClientAccessControlService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/CftQueryService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilter.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentSearchData.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskQuerySpecification.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskResourceDao.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskResourceQueryBuilder.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/SearchTaskRequestMapper.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/Users.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceCustomRepositoryImpl.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskMapper.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaHelper.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CaseConfigurationProviderService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/DmnEvaluationService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/RoleAssignmentVerificationService.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskAutoAssignmentService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/tasktype/TaskTypeTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateOriginEarliestCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateOriginRefCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/IntermediateDateOriginEarliestCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/IntermediateDateOriginLatestCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/IntermediateDateOriginRefCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/NextHearingDateOriginEarliestCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/NextHearingDateOriginRefCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/PriorityDateOriginEarliestCalculatorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/PriorityDateOriginRefCalculatorTest.java
https://tools.hmcts.net/jira/browse/RWA-3563 
```
[ ] Yes
[ ] No
```
=> RWA-3563: Fixed Sonar issues

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-3731
=> Increasing SKU for performance issue

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-3731
=> Rwa 3731 performance degradation

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/ReplicaBaseTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/schedulers/LogicalReplicationCreatorScheduler.java
https://tools.hmcts.net/jira/browse/RWA-3731
Update schedule to run every 30 sec
```
[ ] Yes
[x] No
```
=> RWA-3731 LogicalReplicationCreatorScheduler update

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseServiceSearchTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/search/SortField.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskSearchSortProvider.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceCustomRepositoryImplTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskSearchSortProviderTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/config/RestApiActions.java
https://tools.hmcts.net/jira/browse/RWA-3756
Fix flaky test
```
[ ] Yes
[x] No
```
=> RWA-3756 - Fix flaky test

src/main/resources/db/migration/V1.0.31__add_idx_case_id_on_tasks_table.sql
https://tools.hmcts.net/jira/browse/RWA-3779
=> Adding index for case_id on tasks table

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskCompleteByIdControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/Assertions.java
https://tools.hmcts.net/jira/browse/RWA-3783
Fix one of the flaky test
```
[ ] Yes
[x] No
```
=> RWA-3783 - Fix flaky test

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3759
```
[ ] Yes
[x] No
```
=> RWA-3759: Extend Suppressions

config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskSearchControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/services/AuthorizationProvider.java
https://tools.hmcts.net/jira/browse/RWA-3803
fix flaky test
```
[ ] Yes
[x] No
```
=> RWA-3803 - Fix flaky test

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/MarkTaskReconfigurationService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/MarkTaskReconfigurationServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-3744 
```
[ ] Yes
[ ] No
```
=> RWA-3744: DMN reconfig improvement

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseService.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTTaskDatabaseServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-3842
=> Logs to output volume of Role Assignments during search requests.

src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/permission/PermissionRequirementBuilderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceUnitTest.java
https://tools.hmcts.net/jira/browse/RWA-3814 
```
[ ] Yes
[ ] No
```
=> RWA-3814: Code smells fixes

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3880
extend CVE suppression dates
```
[ ] Yes
[x] No
```
=> RWA-3880 extend suppression date

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/SearchTaskRequest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/TaskOperationRequest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/camunda/SecurityClassification.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/task/WorkType.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/OffsetPageableRequestTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/camunda/CamundaObjectMapperTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CamundaServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ReplicationCheckerTest.java
https://tools.hmcts.net/jira/browse/RWA-3951
made various changed based on the following sonarcloud filter. 
https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=CONSISTENT&issueStatuses=OPEN%2CCONFIRMED&id=uk.gov.hmcts.reform%3Awa-task-management-api 
```
[ ] Yes
[X] No
```
=> RWA-3951 - review and updated consistency issues

src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/auth/permission/PermissionRequirementBuilderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilterTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskResourceSpecificationTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchTestingControllerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/SearchTaskRequestMapperTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/response/GetTasksCompletableResponseTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/entity/WorkTypeResourceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/repository/TaskResourceCustomRepositoryImplTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTSensitiveTaskEventLogsDatabaseServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTSensitiveTaskEventLogsDatabaseServiceUnitTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/RoleSignatureBuilderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/SearchFilterSignatureBuilderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskEntityToReconfigureInputVariableDefMapperTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskSearchSortProviderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateTypeConfiguratorOrderTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateTypeConfiguratorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/ReplicationCheckerTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/TaskOperationServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/UpdateSearchIndexServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/InputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/RWA-3954
remove public from classes and methods
```
[ ] Yes
[X] No
```
=> removed public from classes and methods

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReplicaReportingServiceTest.java, src/main/resources/dbreplica/migration/V1.0.34__reportable_task_plsql.sql
https://tools.hmcts.net/jira/browse/RWA-3976
PowerBi - add the service name for ST_CIC and case type
```
[ ] Yes
[x] No
```
=> RWA-3976 PowerBi - add the service name for ST_CIC

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskResourceDao.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/TaskSearchController.java
https://tools.hmcts.net/jira/browse/RWA-4002
```
[ ] Yes
[ ] No
```
=> Added logs for analysis

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementService.java
https://tools.hmcts.net/jira/browse/RWA-4015
moved camunda update action just before saving task
```
[ ] Yes
[x] No
```
=> RWA-3185 moved camunda update action just before saving task

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-4008
=> Suppress CVEs while we wait for Springboot 3 upgrade completion

charts/wa-task-management-api/Chart.yaml, charts/wa-task-management-api/values.yaml, src/functionalTest/resources/application-functional.yaml, src/integrationTest/resources/application-integration.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-3213
```
[ ] Yes
[ ] No
```
=> RWA-3213: Whitelist ST on Prod

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/wa/WorkTypeConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/GetWorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/utils/TaskMandatoryFieldsValidatorIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/SearchTaskRequestMapper.java, src/main/resources/db/migration/V1.0.32__add_new_work_types.sql, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-4045
Add new worktypes
```
[ ] Yes
[x] No
```
=> RWA-4045 add new work types for Civil

charts/wa-task-management-api/values.preview.template.yaml, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskInitiateByIdControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-4071
check for the value of flag before running the test
```
[ ] Yes
[x] No
```
=> Rwa 4071 add validation

src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/BaseController.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/ExclusiveTaskActionsController.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/operation/TaskReconfigurationTransactionHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-4077
Updated API doc and a test
```
[ ] Yes
[x] No
```
=> RWA-4077 updated test and updated API doc

config/owasp/suppressions.xml, infrastructure/main.tf, infrastructure/state.tf, infrastructure/variables.tf
Reverts hmcts/wa-task-management-api#1356
=> Revert "CME-124 enable DB alerts"

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-349
Terraform plan says that these will be replaced,
module.sdp_db_user.azurerm_key_vault_secret.sdp_vault_sdp_read_user_name
module.sdp_db_user.azurerm_key_vault_secret.sdp_vault_sdp_read_user_password
so SDP has advised to merge to ITHC first to check changes.
```
[ ] Yes
[ x] No
```
=> CME-349: Upgrade AzureRM ITHC

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-349
```
[ ] Yes
[ x] No
```
=> CME-349: Upgrade AzureRM

config/owasp/suppressions.xml, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-124
```
[ ] Yes
[ ] No
```
=> Cme 124 test db monitoring

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/wa/WorkTypeConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/GetWorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/SearchTaskRequestMapper.java, src/main/resources/db/migration/V1.0.33__add_new_work_types.sql, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-4156
Added the work type 'query_work'
```
[ ] Yes
[X] No
```
=> add query_work type

src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-4020 
```
[ ] Yes
[ ] No
```
=> RWA-4020: SpringBootFunctionalBaseTest 503 code Validation

src/testUtils/java/uk/gov/hmcts/reform/wataskmanagementapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-4213 
```
[ ] Yes
[ ] No
```
=> Nightly dev

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-4266
=> Intermitent test failures

src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/TaskResourceDaoTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/DmnEvaluationServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/MIReportingServiceTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateTypeConfiguratorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/taskmanagementservicetests/InitiateTaskTest.java
[RWA-3995](https://tools.hmcts.net/jira/browse/RWA-3995) fix code smells - Local variable should not shadow class fields
fix code smells
```
[ ] Yes
[x] No
```
=> RWA-3995 fix code smells - Local variable should not shadow class field

README.md, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-3969
=> Reviewed readme and made some updates.

src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/config/DeleteTaskFeatureToggleInterceptorTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/response/GetTaskTypesResponseTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/response/GetTasksCompletableResponseTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/response/GetTasksResponseTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/task/TaskTest.java, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementServiceUnitTest.java
[RWA-3998 ](https://tools.hmcts.net/jira/browse/RWA-3998) fix code smells
fix code smells
no code smells: 
```
[ ] Yes
[x] No
```
=> RWA-3998 fix code smells

build.gradle
https://tools.hmcts.net/jira/browse/RWA-4215 
```
[ ] Yes
[ ] No
```
=> RWA-4215: Worktypes pact issue fix

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateTypeConfiguratorForReconfigurationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/OriginEarliestDateTypeConfiguratorTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/OriginLatestDateTypeConfiguratorTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/OriginRefDateTypeConfiguratorTest.java, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DateCalculator.java
https://tools.hmcts.net/jira/browse/RWA-4245
Update for RWA-4245
```
[ ] Yes
[x] No
```
=> RWA-4245 update dueDateTime to dueDate and add a test

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/wa/WorkTypeConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/WorkTypeProviderTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/GetWorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/WorkTypesControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java, src/integrationTest/resources/scripts/search_task_work_types.sql, src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/request/SearchTaskRequestMapper.java, src/main/resources/db/migration/V1.0.34__add_new_work_types.sql, src/test/java/uk/gov/hmcts/reform/wataskmanagementapi/services/CFTWorkTypeDatabaseServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-4224 
Added the new welsh translation work type
```
[ ] Yes
[X] No
```
=> Welsh Translations Work Type

src/integrationTest/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TerminationProcessColumnAdditionTest.java, src/main/resources/dbreplica/migration/V1.0.35__add_column_termination_process_plsql.sql
https://tools.hmcts.net/jira/browse/RWA-3584
Add column in replica
```
[ ] Yes
[x] No
```
=> RWA-3584 changes

CODEOWNERS
https://tools.hmcts.net/jira/browse/RWA-4241
```
[ ] Yes
[x] No
```
=> RWA-4241: Added codeowners file

SECURITY.md
https://tools.hmcts.net/jira/browse/RWA-4240
```
[ ] Yes
[x] No
```
=> RWA-4240: Added Security.md file

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-4418
=> Add `statement_timeout`

build.gradle
https://tools.hmcts.net/jira/browse/RWA-4450
Reverting pitest to 1.16.3 (last stable version).
```
[ ] Yes
[x] No
```
=> RWA-4450: revert pitest

build.gradle
https://tools.hmcts.net/jira/browse/CME-722
Replaced JitPack with Azure Artifacts and updated hmcts package references
```
[ ] Yes
[X] No
```
=> CME-722 Replaced JitPack with Azure Artifacts

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-4527
=> increasing work_mem

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskReplicationMIControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-4521 
```
[ ] Yes
[ ] No
```
=> RWA-4521: Added awaitality

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskReplicationMIControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-4538
```
[ ] Yes
[ ] No
```
=> RWA-4538: Added awaitality to tests

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskExecuteReconfigureControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-4587 
```
[ ] Yes
[ ] No
```
=> RWA-4587: Refactored the assertions

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CME-656
Remove not needed CVE suppressions
```
[ ] Yes
[x] No
```
=> CME-656 remove not needed CVE suppressions

src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/watasks/controllers/PostTaskReplicationMIControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-4657 
```
[ ] Yes
[ ] No
```
=> RWA-4657: Refactored test case

src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/consumer/wa/WorkTypeConsumerTest.java
https://tools.hmcts.net/jira/browse/RWA-4052 
```
[ ] Yes
[ ] No
```
=> RWA-4052: worktypes pact refactor
